# Language options
language: python
python:
        - "3.6"

cache: pip

git:
    submodules: false

# Install dependencieees
install:
        - pip install -r requirements.txt

before_script:
        - export PYTHONPATH="${PYTHONPATH}:`pwd`"

script: pytest test